#!/bin/bash -e

MODE=$1
PYTHON_VERSION="2.7"

if [ -z "$VIRTUAL_ENV" ] ; then
    echo "You must activate your virtualenv: set '$VIRTUAL_ENV'"
    exit 1
fi

SYSTEM_FRAMEWORK_PYTHON_ROOT="/System/Library/Frameworks/Python.framework/Versions/$PYTHON_VERSION"

PYTHON_BINARY="bin/python$PYTHON_VERSION"
FRAMEWORK_PYTHON="$SYSTEM_FRAMEWORK_PYTHON_ROOT/$PYTHON_BINARY"

VENV_SITE_PACKAGES="$VIRTUAL_ENV/lib/python$PYTHON_VERSION/site-packages"

export PYTHONHOME=$VIRTUAL_ENV
exec "$FRAMEWORK_PYTHON" ${@}
